-- MySQL Script generated by MySQL Workbench
-- 09/12/17 12:51:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema coffee
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `coffee` ;

-- -----------------------------------------------------
-- Schema coffee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coffee` DEFAULT CHARACTER SET utf8 ;
USE `coffee` ;

-- -----------------------------------------------------
-- Table `coffee`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`test` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fragrance` VARCHAR(45) NULL,
  `fragrance_notes` VARCHAR(500) NULL,
  `aroma` VARCHAR(45) NULL,
  `aroma_notes` VARCHAR(500) NULL,
  `flavor` VARCHAR(45) NULL,
  `flavor_notes` VARCHAR(500) NULL,
  `residual_flavor` VARCHAR(45) NULL,
  `residual_flavor_notes` VARCHAR(500) NULL,
  `acidity_notes` VARCHAR(500) NULL,
  `acidity` VARCHAR(45) NULL,
  `body_notes` VARCHAR(500) NULL,
  `body` VARCHAR(45) NULL,
  `uniformity_notes` VARCHAR(500) NULL,
  `uniformity_order` VARCHAR(100) NULL,
  `uniformity` VARCHAR(45) NULL,
  `balance_notes` VARCHAR(500) NULL,
  `balance` VARCHAR(45) NULL,
  `clean_cup_notes` VARCHAR(500) NULL,
  `clean_cup_order` VARCHAR(100) NULL,
  `clean_cup` VARCHAR(45) NULL,
  `sweetness_order` VARCHAR(100) NULL,
  `sweetness_notes` VARCHAR(500) NULL,
  `sweetness` VARCHAR(45) NULL,
  `taster_score` VARCHAR(45) NULL,
  `defect` VARCHAR(45) NULL,
  `defect_notes` VARCHAR(500) NULL,
  `defect_order` VARCHAR(500) NULL,
  `cups` INT NULL,
  `total_score` VARCHAR(45) NULL,
  `notes` VARCHAR(500) NULL,
  `finished` TINYINT NOT NULL DEFAULT 0,
  `disable_score` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee`.`sample`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`sample` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `height` VARCHAR(45) NOT NULL,
  `fr` VARCHAR(45) NULL,
  `humidity` VARCHAR(45) NULL,
  `merma` VARCHAR(45) NULL,
  `pasilla_grams` VARCHAR(45) NULL,
  `pasilla_percentage` VARCHAR(45) NULL,
  `broca_grams` VARCHAR(45) NULL,
  `broca_percentage` VARCHAR(45) NULL,
  `score` VARCHAR(45) NULL,
  `test_id` INT UNSIGNED NULL,
  `almond_total` VARCHAR(45) NULL,
  `almond_healthy` VARCHAR(45) NULL,
  `notes_physical_analysis` VARCHAR(500) NULL,
  `grower` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `grower_id` VARCHAR(45) NULL,
  `location` VARCHAR(100) NULL,
  `departament` VARCHAR(100) NULL,
  `municipality_grower` VARCHAR(100) NULL,
  `vereda_grower` VARCHAR(100) NULL,
  `variety` VARCHAR(45) NULL,
  `date` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_sample_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `coffee`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `code_UNIQUE` ON `coffee`.`sample` (`code` ASC);

CREATE INDEX `fk_sample_test1_idx` ON `coffee`.`sample` (`test_id` ASC);


-- -----------------------------------------------------
-- Table `coffee`.`attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`attribute` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `attribute_UNIQUE` ON `coffee`.`attribute` (`name` ASC);


-- -----------------------------------------------------
-- Table `coffee`.`attributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`attributes` (
  `test_id` INT UNSIGNED NOT NULL,
  `attribute_id` INT NOT NULL,
  PRIMARY KEY (`test_id`, `attribute_id`),
  CONSTRAINT `fk_attributes_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `coffee`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attributes_attribute1`
    FOREIGN KEY (`attribute_id`)
    REFERENCES `coffee`.`attribute` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_attributes_attribute1_idx` ON `coffee`.`attributes` (`attribute_id` ASC);


-- -----------------------------------------------------
-- Table `coffee`.`persistent_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`persistent_login` (
  `series` VARCHAR(64) NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  `username` VARCHAR(64) NOT NULL,
  `last_used` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`series`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `birthdate` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `type_UNIQUE` ON `coffee`.`role` (`type` ASC);


-- -----------------------------------------------------
-- Table `coffee`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`roles` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  CONSTRAINT `fk_roles_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `coffee`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `coffee`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_roles_role1_idx` ON `coffee`.`roles` (`role_id` ASC);


-- -----------------------------------------------------
-- Table `coffee`.`panel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`panel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `authorization_date` TIMESTAMP NULL,
  `realization_date` TIMESTAMP NULL,
  `finished` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`tests` (
  `test_id` INT UNSIGNED NOT NULL,
  `sample_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `panel_id` INT NOT NULL,
  PRIMARY KEY (`test_id`, `sample_id`, `user_id`, `panel_id`),
  CONSTRAINT `fk_tests_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `coffee`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tests_sample1`
    FOREIGN KEY (`sample_id`)
    REFERENCES `coffee`.`sample` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tests_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `coffee`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tests_panel1`
    FOREIGN KEY (`panel_id`)
    REFERENCES `coffee`.`panel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tests_test1_idx` ON `coffee`.`tests` (`test_id` ASC);

CREATE INDEX `fk_tests_sample1_idx` ON `coffee`.`tests` (`sample_id` ASC);

CREATE INDEX `fk_tests_user1_idx` ON `coffee`.`tests` (`user_id` ASC);

CREATE INDEX `fk_tests_panel1_idx` ON `coffee`.`tests` (`panel_id` ASC);


-- -----------------------------------------------------
-- Table `coffee`.`password_reset_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`password_reset_token` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(100) NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_password_reset_token_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `coffee`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_password_reset_token_user1_idx` ON `coffee`.`password_reset_token` (`user_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


/* Populate USER_PROFILE Table */
INSERT INTO ROLE(id,type) VALUES (1,'TASTER');
INSERT INTO ROLE(id,type) VALUES (2,'ADMIN');
INSERT INTO ROLE(id,type) VALUES (3,'ORGANIZER');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (1,'fruity','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (2,'berry','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (3,'strawberry','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (4,'raspberry','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (5,'blueberry','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (6,'blackberry','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (7,'dried-fruit','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (8,'raisin','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (9,'prune','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (10,'other-fruit','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (11,'apple','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (12,'pear','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (13,'peach','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (14,'grape','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (15,'cherry','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (16,'pomegranate','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (17,'coconut','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (18,'pineapple','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (19,'citrus-fruit','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (20,'lemon','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (21,'grapefruit','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (22,'orange','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (23,'lime','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (24,'sour','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (25,'sour-aromatics','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (31,'alcohol','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (33,'winey','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (34,'fermented','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (35,'overripe/near-fermented','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (36,'olive-oil','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (37,'raw','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (38,'under-ripe','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (39,'peapod','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (40,'green','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (41,'fresh','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (42,'dark-green','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (43,'vegetative','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (44,'hay-like','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (45,'herb-like','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (46,'beany','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (47,'stale','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (48,'papery','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (49,'cardboard','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (50,'musty/earthy','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (51,'musty/dusty','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (52,'moldy/damp','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (53,'phenolic','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (54,'animalic','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (55,'meaty/brothy','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (56,'woody','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (57,'bitter','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (58,'salty','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (59,'medicinal','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (60,'rubber','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (61,'petroleum','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (62,'skunky','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (63,'tobacco','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (64,'pipe-tobacco','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (65,'acrid','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (66,'ashy','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (67,'burnt','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (68,'smoky','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (69,'roasted','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (70,'brown-roast','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (71,'grain','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (72,'malt','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (73,'pungent','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (74,'pepper','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (75,'anise','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (76,'nutmeg','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (77,'brown-spice','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (78,'cinnamon','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (79,'clove','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (80,'nutty','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (81,'almond','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (82,'hazelnut','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (83,'peanuts','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (84,'cocoa','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (85,'chocolate','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (86,'dark-chocolate','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (87,'sweet','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (88,'molasses','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (89,'maple-syrup','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (90,'brown-sugar','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (91,'caramelized','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (92,'honey','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (93,'vanilla','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (94,'vanillin','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (95,'sweet-aromatics','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (96,'overall-sweet','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (97,'floral','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (98,'rose','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (99,'jasmine','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (100,'chamomile','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (101,'black-tea','a');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (106,'mouth-drying','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (107,'thickness','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (108,'metallic','d');
INSERT INTO ATTRIBUTE(id,name,type) VALUES (109,'oily','d');