package com.spring.coffee.model;
// Generated 12/09/2017 01:17:12 PM by Hibernate Tools 5.2.5.Final

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Attribute generated by hbm2java
 */
@Entity
@Table(name = "attribute", catalog = "coffee", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Attribute implements java.io.Serializable {

	private Integer id;
	private String name;
	private String type;
	// private Set<Test> tests = new HashSet<Test>(0);

	public Attribute() {
	}

	public Attribute(String name) {
		this.name = name;
	}

	public Attribute(String name, String type, Set<Test> tests) {
		this.name = name;
		this.type = type;
		// this.tests = tests;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Override
	public String toString() {
		return "Attribute [id=" + id + ", name=" + name + ", type=" + type + "]";
	}

	/*
	 * @ManyToMany(fetch = FetchType.LAZY)
	 * 
	 * @JoinTable(name = "attributes", catalog = "coffee", joinColumns = {
	 * 
	 * @JoinColumn(name = "attribute_id", nullable = false, updatable = false) },
	 * inverseJoinColumns = {
	 * 
	 * @JoinColumn(name = "test_id", nullable = false, updatable = false) }) public
	 * Set<Test> getTests() { return this.tests; }
	 * 
	 * public void setTests(Set<Test> tests) { this.tests = tests; }
	 */

}
