package com.spring.coffee.model;
// Generated 12/09/2017 01:17:12 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersistentLogin generated by hbm2java
 */
@Entity
@Table(name = "persistent_login", catalog = "coffee")
public class PersistentLogin implements java.io.Serializable {

	private String series;
	private String token;
	private String username;
	private Date lastUsed;

	public PersistentLogin() {
	}

	public PersistentLogin(String series, String token, String username, Date lastUsed) {
		this.series = series;
		this.token = token;
		this.username = username;
		this.lastUsed = lastUsed;
	}

	@Id

	@Column(name = "series", unique = true, nullable = false, length = 64)
	public String getSeries() {
		return this.series;
	}

	public void setSeries(String series) {
		this.series = series;
	}

	@Column(name = "token", nullable = false, length = 64)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_used", nullable = false, length = 19)
	public Date getLastUsed() {
		return this.lastUsed;
	}

	public void setLastUsed(Date lastUsed) {
		this.lastUsed = lastUsed;
	}

	@Override
	public String toString() {
		return "PersistentLogin [series=" + series + ", token=" + token + ", username=" + username + ", lastUsed="
				+ lastUsed + "]";
	}

}
