package com.spring.coffee.model;
// Generated 12/09/2017 01:17:12 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Sample generated by hbm2java
 */
@Entity
@Table(name = "sample", catalog = "coffee", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Sample implements java.io.Serializable {

	private Integer id;
	private Test test;
	private String code;
	private String height;
	private String fr;
	private String humidity;
	private String merma;
	private String pasillaGrams;
	private String pasillaPercentage;
	private String brocaGrams;
	private String brocaPercentage;
	private String score;
	private String almondTotal;
	private String almondHealthy;
	private String notesPhysicalAnalysis;
	private String grower;
	private String phone;
	private String growerId;
	private String location;
	private String departament;
	private String municipalityGrower;
	private String veredaGrower;
	private String variety;
	private Date date;
	private Set<Tests> testses = new HashSet<Tests>(0);

	public Sample() {
	}

	public Sample(String code, String height) {
		this.code = code;
		this.height = height;
	}

	public Sample(Test test, String code, String height, String fr, String humidity, String merma, String pasillaGrams,
			String pasillaPercentage, String brocaGrams, String brocaPercentage, String score, String almondTotal,
			String almondHealthy, String notesPhysicalAnalysis, String grower, String phone, String growerId,
			String location, String departament, String municipalityGrower, String veredaGrower, String variety,
			Date date, Set<Tests> testses) {
		this.test = test;
		this.code = code;
		this.height = height;
		this.fr = fr;
		this.humidity = humidity;
		this.merma = merma;
		this.pasillaGrams = pasillaGrams;
		this.pasillaPercentage = pasillaPercentage;
		this.brocaGrams = brocaGrams;
		this.brocaPercentage = brocaPercentage;
		this.score = score;
		this.almondTotal = almondTotal;
		this.almondHealthy = almondHealthy;
		this.notesPhysicalAnalysis = notesPhysicalAnalysis;
		this.grower = grower;
		this.phone = phone;
		this.growerId = growerId;
		this.location = location;
		this.departament = departament;
		this.municipalityGrower = municipalityGrower;
		this.veredaGrower = veredaGrower;
		this.variety = variety;
		this.date = date;
		this.testses = testses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "test_id")
	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	@Column(name = "code", unique = true, nullable = false, length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "height", nullable = false, length = 45)
	public String getHeight() {
		return this.height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	@Column(name = "fr", length = 45)
	public String getFr() {
		return this.fr;
	}

	public void setFr(String fr) {
		this.fr = fr;
	}

	@Column(name = "humidity", length = 45)
	public String getHumidity() {
		return this.humidity;
	}

	public void setHumidity(String humidity) {
		this.humidity = humidity;
	}

	@Column(name = "merma", length = 45)
	public String getMerma() {
		return this.merma;
	}

	public void setMerma(String merma) {
		this.merma = merma;
	}

	@Column(name = "pasilla_grams", length = 45)
	public String getPasillaGrams() {
		return this.pasillaGrams;
	}

	public void setPasillaGrams(String pasillaGrams) {
		this.pasillaGrams = pasillaGrams;
	}

	@Column(name = "pasilla_percentage", length = 45)
	public String getPasillaPercentage() {
		return this.pasillaPercentage;
	}

	public void setPasillaPercentage(String pasillaPercentage) {
		this.pasillaPercentage = pasillaPercentage;
	}

	@Column(name = "broca_grams", length = 45)
	public String getBrocaGrams() {
		return this.brocaGrams;
	}

	public void setBrocaGrams(String brocaGrams) {
		this.brocaGrams = brocaGrams;
	}

	@Column(name = "broca_percentage", length = 45)
	public String getBrocaPercentage() {
		return this.brocaPercentage;
	}

	public void setBrocaPercentage(String brocaPercentage) {
		this.brocaPercentage = brocaPercentage;
	}

	@Column(name = "score", length = 45)
	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	@Column(name = "almond_total", length = 45)
	public String getAlmondTotal() {
		return this.almondTotal;
	}

	public void setAlmondTotal(String almondTotal) {
		this.almondTotal = almondTotal;
	}

	@Column(name = "almond_healthy", length = 45)
	public String getAlmondHealthy() {
		return this.almondHealthy;
	}

	public void setAlmondHealthy(String almondHealthy) {
		this.almondHealthy = almondHealthy;
	}

	@Column(name = "notes_physical_analysis", length = 500)
	public String getNotesPhysicalAnalysis() {
		return this.notesPhysicalAnalysis;
	}

	public void setNotesPhysicalAnalysis(String notesPhysicalAnalysis) {
		this.notesPhysicalAnalysis = notesPhysicalAnalysis;
	}

	@Column(name = "grower", length = 45)
	public String getGrower() {
		return this.grower;
	}

	public void setGrower(String grower) {
		this.grower = grower;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "grower_id", length = 45)
	public String getGrowerId() {
		return this.growerId;
	}

	public void setGrowerId(String growerId) {
		this.growerId = growerId;
	}

	@Column(name = "location", length = 100)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "departament", length = 100)
	public String getDepartament() {
		return this.departament;
	}

	public void setDepartament(String departament) {
		this.departament = departament;
	}

	@Column(name = "municipality_grower", length = 100)
	public String getMunicipalityGrower() {
		return this.municipalityGrower;
	}

	public void setMunicipalityGrower(String municipalityGrower) {
		this.municipalityGrower = municipalityGrower;
	}

	@Column(name = "vereda_grower", length = 100)
	public String getVeredaGrower() {
		return this.veredaGrower;
	}

	public void setVeredaGrower(String veredaGrower) {
		this.veredaGrower = veredaGrower;
	}

	@Column(name = "variety", length = 45)
	public String getVariety() {
		return this.variety;
	}

	public void setVariety(String variety) {
		this.variety = variety;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "sample")
	public Set<Tests> getTestses() {
		return this.testses;
	}

	public void setTestses(Set<Tests> testses) {
		this.testses = testses;
	}

	@Override
	public String toString() {
		return "Sample [id=" + id + ", test=" + test + ", code=" + code + ", height=" + height + ", fr=" + fr
				+ ", humidity=" + humidity + ", merma=" + merma + ", pasillaGrams=" + pasillaGrams
				+ ", pasillaPercentage=" + pasillaPercentage + ", brocaGrams=" + brocaGrams + ", brocaPercentage="
				+ brocaPercentage + ", score=" + score + ", almondTotal=" + almondTotal + ", almondHealthy="
				+ almondHealthy + ", notesPhysicalAnalysis=" + notesPhysicalAnalysis + ", grower=" + grower + ", phone="
				+ phone + ", growerId=" + growerId + ", location=" + location + ", departament=" + departament
				+ ", municipalityGrower=" + municipalityGrower + ", veredaGrower=" + veredaGrower + ", variety="
				+ variety + ", date=" + date + "]";
	}

}
