package com.spring.coffee.model;
// Generated 12/09/2017 01:17:12 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tests generated by hbm2java
 */
@Entity
@Table(name = "tests", catalog = "coffee")
public class Tests implements java.io.Serializable {

	private TestsId id;
	private Panel panel;
	private Sample sample;
	private Test test;
	private User user;

	public Tests() {
	}

	public Tests(TestsId id) {
		this.id = id;
	}

	public Tests(TestsId id, Panel panel, Sample sample, Test test, User user) {
		this.id = id;
		this.panel = panel;
		this.sample = sample;
		this.test = test;
		this.user = user;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "testId", column = @Column(name = "test_id", nullable = false)),
			@AttributeOverride(name = "sampleId", column = @Column(name = "sample_id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "panelId", column = @Column(name = "panel_id", nullable = false)) })
	public TestsId getId() {
		return this.id;
	}

	public void setId(TestsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "panel_id", nullable = false, insertable = false, updatable = false)
	public Panel getPanel() {
		return this.panel;
	}

	public void setPanel(Panel panel) {
		this.panel = panel;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sample_id", nullable = false, insertable = false, updatable = false)
	public Sample getSample() {
		return this.sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "test_id", nullable = false, insertable = false, updatable = false)
	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Override
	public String toString() {
		return "Tests [id=" + id + ", panel=" + panel + ", sample=" + sample + ", test=" + test + ", user=" + user
				+ "]";
	}

}
