package com.spring.coffee.model;
// Generated 12/09/2017 01:17:12 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "test", catalog = "coffee")
public class Test implements java.io.Serializable {

	private Integer id;
	private String fragrance;
	private String fragranceNotes;
	private String aroma;
	private String aromaNotes;
	private String flavor;
	private String flavorNotes;
	private String residualFlavor;
	private String residualFlavorNotes;
	private String acidityNotes;
	private String acidity;
	private String bodyNotes;
	private String body;
	private String uniformityNotes;
	private String uniformityOrder;
	private String uniformity;
	private String balanceNotes;
	private String balance;
	private String cleanCupNotes;
	private String cleanCupOrder;
	private String cleanCup;
	private String sweetnessOrder;
	private String sweetnessNotes;
	private String sweetness;
	private String tasterScore;
	private String defect;
	private String defectNotes;
	private String defectOrder;
	private Integer cups;
	private String totalScore;
	private String notes;
	private byte finished;
	private byte disableScore;
	// private Set<Sample> samples = new HashSet<Sample>(0);
	private Set<Attribute> attributes = new HashSet<Attribute>(0);
	// private Set<Tests> testses = new HashSet<Tests>(0);

	public Test() {
	}

	public Test(byte finished, byte disableScore) {
		this.finished = finished;
		this.disableScore = disableScore;
	}

	public Test(String fragrance, String fragranceNotes, String aroma, String aromaNotes, String flavor,
			String flavorNotes, String residualFlavor, String residualFlavorNotes, String acidityNotes, String acidity,
			String bodyNotes, String body, String uniformityNotes, String uniformityOrder, String uniformity,
			String balanceNotes, String balance, String cleanCupNotes, String cleanCupOrder, String cleanCup,
			String sweetnessOrder, String sweetnessNotes, String sweetness, String tasterScore, String defect,
			String defectNotes, String defectOrder, Integer cups, String totalScore, String notes, byte finished,
			byte disableScore, Set<Sample> samples, Set<Attribute> attributes, Set<Tests> testses) {
		this.fragrance = fragrance;
		this.fragranceNotes = fragranceNotes;
		this.aroma = aroma;
		this.aromaNotes = aromaNotes;
		this.flavor = flavor;
		this.flavorNotes = flavorNotes;
		this.residualFlavor = residualFlavor;
		this.residualFlavorNotes = residualFlavorNotes;
		this.acidityNotes = acidityNotes;
		this.acidity = acidity;
		this.bodyNotes = bodyNotes;
		this.body = body;
		this.uniformityNotes = uniformityNotes;
		this.uniformityOrder = uniformityOrder;
		this.uniformity = uniformity;
		this.balanceNotes = balanceNotes;
		this.balance = balance;
		this.cleanCupNotes = cleanCupNotes;
		this.cleanCupOrder = cleanCupOrder;
		this.cleanCup = cleanCup;
		this.sweetnessOrder = sweetnessOrder;
		this.sweetnessNotes = sweetnessNotes;
		this.sweetness = sweetness;
		this.tasterScore = tasterScore;
		this.defect = defect;
		this.defectNotes = defectNotes;
		this.defectOrder = defectOrder;
		this.cups = cups;
		this.totalScore = totalScore;
		this.notes = notes;
		this.finished = finished;
		this.disableScore = disableScore;
		// this.samples = samples;
		this.attributes = attributes;
		// this.testses = testses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "fragrance", length = 45)
	public String getFragrance() {
		return this.fragrance;
	}

	public void setFragrance(String fragrance) {
		this.fragrance = fragrance;
	}

	@Column(name = "fragrance_notes", length = 500)
	public String getFragranceNotes() {
		return this.fragranceNotes;
	}

	public void setFragranceNotes(String fragranceNotes) {
		this.fragranceNotes = fragranceNotes;
	}

	@Column(name = "aroma", length = 45)
	public String getAroma() {
		return this.aroma;
	}

	public void setAroma(String aroma) {
		this.aroma = aroma;
	}

	@Column(name = "aroma_notes", length = 500)
	public String getAromaNotes() {
		return this.aromaNotes;
	}

	public void setAromaNotes(String aromaNotes) {
		this.aromaNotes = aromaNotes;
	}

	@Column(name = "flavor", length = 45)
	public String getFlavor() {
		return this.flavor;
	}

	public void setFlavor(String flavor) {
		this.flavor = flavor;
	}

	@Column(name = "flavor_notes", length = 500)
	public String getFlavorNotes() {
		return this.flavorNotes;
	}

	public void setFlavorNotes(String flavorNotes) {
		this.flavorNotes = flavorNotes;
	}

	@Column(name = "residual_flavor", length = 45)
	public String getResidualFlavor() {
		return this.residualFlavor;
	}

	public void setResidualFlavor(String residualFlavor) {
		this.residualFlavor = residualFlavor;
	}

	@Column(name = "residual_flavor_notes", length = 500)
	public String getResidualFlavorNotes() {
		return this.residualFlavorNotes;
	}

	public void setResidualFlavorNotes(String residualFlavorNotes) {
		this.residualFlavorNotes = residualFlavorNotes;
	}

	@Column(name = "acidity_notes", length = 500)
	public String getAcidityNotes() {
		return this.acidityNotes;
	}

	public void setAcidityNotes(String acidityNotes) {
		this.acidityNotes = acidityNotes;
	}

	@Column(name = "acidity", length = 45)
	public String getAcidity() {
		return this.acidity;
	}

	public void setAcidity(String acidity) {
		this.acidity = acidity;
	}

	@Column(name = "body_notes", length = 500)
	public String getBodyNotes() {
		return this.bodyNotes;
	}

	public void setBodyNotes(String bodyNotes) {
		this.bodyNotes = bodyNotes;
	}

	@Column(name = "body", length = 45)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "uniformity_notes", length = 500)
	public String getUniformityNotes() {
		return this.uniformityNotes;
	}

	public void setUniformityNotes(String uniformityNotes) {
		this.uniformityNotes = uniformityNotes;
	}

	@Column(name = "uniformity_order", length = 100)
	public String getUniformityOrder() {
		return this.uniformityOrder;
	}

	public void setUniformityOrder(String uniformityOrder) {
		this.uniformityOrder = uniformityOrder;
	}

	@Column(name = "uniformity", length = 45)
	public String getUniformity() {
		return this.uniformity;
	}

	public void setUniformity(String uniformity) {
		this.uniformity = uniformity;
	}

	@Column(name = "balance_notes", length = 500)
	public String getBalanceNotes() {
		return this.balanceNotes;
	}

	public void setBalanceNotes(String balanceNotes) {
		this.balanceNotes = balanceNotes;
	}

	@Column(name = "balance", length = 45)
	public String getBalance() {
		return this.balance;
	}

	public void setBalance(String balance) {
		this.balance = balance;
	}

	@Column(name = "clean_cup_notes", length = 500)
	public String getCleanCupNotes() {
		return this.cleanCupNotes;
	}

	public void setCleanCupNotes(String cleanCupNotes) {
		this.cleanCupNotes = cleanCupNotes;
	}

	@Column(name = "clean_cup_order", length = 100)
	public String getCleanCupOrder() {
		return this.cleanCupOrder;
	}

	public void setCleanCupOrder(String cleanCupOrder) {
		this.cleanCupOrder = cleanCupOrder;
	}

	@Column(name = "clean_cup", length = 45)
	public String getCleanCup() {
		return this.cleanCup;
	}

	public void setCleanCup(String cleanCup) {
		this.cleanCup = cleanCup;
	}

	@Column(name = "sweetness_order", length = 100)
	public String getSweetnessOrder() {
		return this.sweetnessOrder;
	}

	public void setSweetnessOrder(String sweetnessOrder) {
		this.sweetnessOrder = sweetnessOrder;
	}

	@Column(name = "sweetness_notes", length = 500)
	public String getSweetnessNotes() {
		return this.sweetnessNotes;
	}

	public void setSweetnessNotes(String sweetnessNotes) {
		this.sweetnessNotes = sweetnessNotes;
	}

	@Column(name = "sweetness", length = 45)
	public String getSweetness() {
		return this.sweetness;
	}

	public void setSweetness(String sweetness) {
		this.sweetness = sweetness;
	}

	@Column(name = "taster_score", length = 45)
	public String getTasterScore() {
		return this.tasterScore;
	}

	public void setTasterScore(String tasterScore) {
		this.tasterScore = tasterScore;
	}

	@Column(name = "defect", length = 45)
	public String getDefect() {
		return this.defect;
	}

	public void setDefect(String defect) {
		this.defect = defect;
	}

	@Column(name = "defect_notes", length = 500)
	public String getDefectNotes() {
		return this.defectNotes;
	}

	public void setDefectNotes(String defectNotes) {
		this.defectNotes = defectNotes;
	}

	@Column(name = "defect_order", length = 500)
	public String getDefectOrder() {
		return this.defectOrder;
	}

	public void setDefectOrder(String defectOrder) {
		this.defectOrder = defectOrder;
	}

	@Column(name = "cups")
	public Integer getCups() {
		return this.cups;
	}

	public void setCups(Integer cups) {
		this.cups = cups;
	}

	@Column(name = "total_score", length = 45)
	public String getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(String totalScore) {
		this.totalScore = totalScore;
	}

	@Column(name = "notes", length = 500)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "finished", nullable = false)
	public byte getFinished() {
		return this.finished;
	}

	public void setFinished(byte finished) {
		this.finished = finished;
	}

	@Column(name = "disable_score", nullable = false)
	public byte getDisableScore() {
		return this.disableScore;
	}

	public void setDisableScore(byte disableScore) {
		this.disableScore = disableScore;
	}

	/*
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "test") public Set<Sample>
	 * getSamples() { return this.samples; }
	 * 
	 * public void setSamples(Set<Sample> samples) { this.samples = samples; }
	 */

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "attributes", catalog = "coffee", joinColumns = {
			@JoinColumn(name = "test_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "attribute_id", nullable = false, updatable = false) })
	public Set<Attribute> getAttributes() {
		return this.attributes;
	}

	public void setAttributes(Set<Attribute> attributes) {
		this.attributes = attributes;
	}

	@Override
	public String toString() {
		return "Test [id=" + id + ", fragrance=" + fragrance + ", fragranceNotes=" + fragranceNotes + ", aroma=" + aroma
				+ ", aromaNotes=" + aromaNotes + ", flavor=" + flavor + ", flavorNotes=" + flavorNotes
				+ ", residualFlavor=" + residualFlavor + ", residualFlavorNotes=" + residualFlavorNotes
				+ ", acidityNotes=" + acidityNotes + ", acidity=" + acidity + ", bodyNotes=" + bodyNotes + ", body="
				+ body + ", uniformityNotes=" + uniformityNotes + ", uniformityOrder=" + uniformityOrder
				+ ", uniformity=" + uniformity + ", balanceNotes=" + balanceNotes + ", balance=" + balance
				+ ", cleanCupNotes=" + cleanCupNotes + ", cleanCupOrder=" + cleanCupOrder + ", cleanCup=" + cleanCup
				+ ", sweetnessOrder=" + sweetnessOrder + ", sweetnessNotes=" + sweetnessNotes + ", sweetness="
				+ sweetness + ", tasterScore=" + tasterScore + ", defect=" + defect + ", defectNotes=" + defectNotes
				+ ", defectOrder=" + defectOrder + ", cups=" + cups + ", totalScore=" + totalScore + ", notes=" + notes
				+ ", finished=" + finished + ", disableScore=" + disableScore + ", attributes=" + attributes + "]";
	}

	/*
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "test") public Set<Tests>
	 * getTestses() { return this.testses; }
	 * 
	 * public void setTestses(Set<Tests> testses) { this.testses = testses; }
	 */

}
